"""modify table site

Revision ID: b4e1bbb80d6e
Revises: 8c832915417d
Create Date: 2018-11-14 09:24:16.730288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e1bbb80d6e'
down_revision = '8c832915417d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'site', 'category', ['category_id'], ['id'])
    op.drop_column('site', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.drop_column('site', 'category_id')
    # ### end Alembic commands ###
